
name: freebsd

on: [workflow_dispatch]

jobs:
  runshell:
    runs-on: ubuntu-22.04
    name: Start a freebsd shell
    steps:
    - uses: vmactions/cf-tunnel@v0
      id: tunnel
      with:
        protocol: http
        port: 8000
    - name: Set envs
      run: echo "TestingDomain=${{steps.tunnel.outputs.server}}" >> $GITHUB_ENV
    - name: Starting a freebsd VM, please wait. It may take 5 minutes
      id: shell
      uses: vmactions/freebsd-vm@main
      with:
        nat: |
          "8000": "80"
        envs: 'TestingDomain TEST_PREFERRED_CHAIN TEST_ACME_Server INPUT_*'
        sync: sshfs
        prepare: pkg install -y socat curl
        run: |
          pwd
          ls -lah
          whoami
          env
          freebsd-version
          (ls -lah)
    - name: Sleep
      run: for i in $(seq 1 10) ; do echo $i; sleep 1; done
    - name: ssh into freebsd
      run: |
        ssh freebsd
        fetch https://github.com/freebsd/freebsd-src/archive/refs/heads/main.zip && unzip -q main.zip
        mkdir kernel
        cd freebsd-src-main/sys/amd64/conf
        cp GENERIC-NODEBUG bbr
        sed -i '' -e	's/makeoptions/#makeoptions/g' GENERIC
        echo "
        options         TCPHPTS
        options         RATELIMIT
        makeoptions     WITH_EXTRA_TCP_STACKS=1
        " >> bbr
        cd ../../../
        make -j$(sysctl -n hw.ncpu) kernel KERNCONF=bbr KODIR=/root/kernel
        cd ..
        tar cfJ kernel_amd64.txz kernel
    - uses: fawazahmed0/action-debug@main
      with:
        credentials: "${{ secrets.CREDENTIALS }}"

