#某些老旧的bios可能不支持直接解压镜像到U盘安装，使用ventoy或rufus创建启动盘可解
name: test
on: [workflow_dispatch]
jobs:
  test:
    runs-on: windows-2025-vs2026
    env:
      TZ: Asia/Shanghai
    steps:
    
    - uses: actions/checkout@v6
      with:
        repository: kunitsyn/ogg-acm-codec
        
    - name: build
      run: |
        cd src/vorbisacm
        devenv.exe vorbisacm.sln

    - uses: fawazahmed0/action-debug@main
      with:
        credentials: "${{ secrets.CREDENTIALS }}"
