name: test
on: [workflow_dispatch]
jobs:
  create:
    runs-on: windows-2022
    env:
      CREDENTIALS: ${{ secrets.CREDENTIALS }}
      TZ: Asia/Shanghai
    steps:
    - name: prepare
      run: |
        curl -OL https://github.com/Aniark/debug/releases/download/aac_at/19045.6396_amd64_zh-cn_professional_fd91b7ad_convert.zip
        unzip *_convert.zip
        sed -i 's/SkipEdge     =0/SkipEdge     =1/' ConvertConfig.ini
        sed -i 's/SkipWinRE    =0/SkipWinRE    =1/' ConvertConfig.ini
        sed -i 's/ResetBase    =0/ResetBase    =1/' ConvertConfig.ini
        sed -i 's/AutoExit     =1/AutoExit     =0/' ConvertConfig.ini
    - name: 7z
      run: |
        7z -mx0 a release/win10_19045.6396.7z -v4k *.zip -mx0
        pwd
        ls release
