#某些老旧的bios可能不支持直接解压镜像到U盘安装，使用ventoy或rufus创建启动盘可解
name: test
on: [workflow_dispatch]
jobs:
  test:
    runs-on: windows-2019
    env:
      TZ: Asia/Shanghai
    steps:
    
    - uses: actions/checkout@v6
      with:
        repository: kunitsyn/ogg-acm-codec
      
    - uses: TheMrMilchmann/setup-msvc-dev@v4
      with:
        arch: x64
        sdk: 10.0.17763.0
        toolset: 14.0
        
    - name: build
      run: |
        cd src/vorbisacm

    - uses: fawazahmed0/action-debug@main
      with:
        credentials: "${{ secrets.CREDENTIALS }}"
