name: web-linux
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CREDENTIALS: ${{ secrets.CREDENTIALS }}
    steps:
    - uses: fawazahmed0/action-debug@main
      with:
        credentials: "${{ secrets.CREDENTIALS }}"
