name: web-mac
on: [workflow_dispatch]
jobs:
  build:
    runs-on: macos-latest
    env:
      CREDENTIALS: ${{ secrets.CREDENTIALS }}
    steps:
    - uses: docker-practice/actions-setup-docker@master
    - uses: fawazahmed0/action-debug@main
      with:
        credentials: "${{ secrets.CREDENTIALS }}"
