name: web-mac-port
on: [workflow_dispatch]
jobs:
  build:
    runs-on: macos-latest
    env:
      CREDENTIALS: ${{ secrets.CREDENTIALS }}
    steps:
    - uses: melusina-org/setup-macports@v1
    - uses: fawazahmed0/action-debug@main
      with:
        credentials: "${{ secrets.CREDENTIALS }}"
