name: web-linux-arm64
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-24.04-arm
    env:
      CREDENTIALS: ${{ secrets.CREDENTIALS }}
    steps:
    - uses: Aniark/debug@main
      with:
        credentials: "${{ secrets.CREDENTIALS }}"
