name: win10
on: [workflow_dispatch]
jobs:
  create:
    runs-on: windows-2022
    env:
      CREDENTIALS: ${{ secrets.CREDENTIALS }}
      TZ: Asia/Shanghai
    steps:
    - name: prepare
      run: |
        curl -OL https://github.com/Aniark/debug/releases/download/aac_at/19045.6396_amd64_zh-cn_professional_fd91b7ad_convert.zip
        unzip *_convert.zip
        sed -i 's/SkipEdge     =0/SkipEdge     =1/' ConvertConfig.ini
        #sed -i 's/SkipWinRE    =0/SkipWinRE    =1/' ConvertConfig.ini
        sed -i 's/ResetBase    =0/ResetBase    =1/' ConvertConfig.ini
        sed -i 's/AutoExit     =0/AutoExit     =1/' ConvertConfig.ini
        #sed -i 's/AddUpdates   =1/AddUpdates   =0/' ConvertConfig.ini
        sed -i 's/wim2esd      =1/wim2esd      =0/' ConvertConfig.ini
    - name: run
      run: |
        powershell ./uup_download_windows.cmd
    - name: 7z
      run: |
        7z -mx0 a release/win10_19045.6396_wim.7z -v2000m *.iso
    - name: release
      uses: softprops/action-gh-release@master
      with:
         tag_name: aac_at
         files: release/*
